### PR TITLE
Adds map to the office world.

### LINKED ISSUE #67: Add map for the office.sdf world
### Summary

- What the title says.
 - After #66 is merged we will have nav2 setup.

### PR DESCRIPTION
**Pull request by francocipollone**
# 🎉 New feature

Closes #67 

## Test it
```
ros2 launch andino_gz andino_gz.launch.py nav2:=True world_name:=office.sdf map:=office
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)

### CODE REVIEW

**Comment by Voldivh** [comment]
@francocipollone I tried it out and it looks fine, however, I noticed this error appearing all the time:
`Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[rviz2-5]          at line 93 in ./src/buffer_core.cpp`

**Review by Voldivh — DISMISSED** [review]

**Comment by francocipollone** [comment]
> @francocipollone I tried it out and it looks fine, however, I noticed this error appearing all the time: `Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist [rviz2-5] at line 93 in ./src/buffer_core.cpp`

Does it happen after sending the initial pose?

**Comment by Voldivh** [comment]
> > @francocipollone I tried it out and it looks fine, however, I noticed this error appearing all the time: `Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist [rviz2-5] at line 93 in ./src/buffer_core.cpp`
> 
> Does it happen after sending the initial pose?

Which command should I use for that? Call the `set_initial_pose` service?

**Comment by Voldivh** [comment]
LGTM!

**Pull request merged**
